# Generated by Django 5.1.4 on 2025-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='medicalimage',
            name='description',
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
