# Generated by Django 5.1.4 on 2025-01-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    MedicalImage = apps.get_model('segmentation', 'MedicalImage')
    default_user = User.objects.first()  # Ensure at least one user exists
    for image in MedicalImage.objects.all():
        if not image.user:
            image.user = default_user
            image.save()

class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_lungsegmentationmodel_medicalimage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_user),
    ]
