# Generated by Django 5.1.4 on 2025-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_alter_medicalimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungSegmentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
