# Generated by Django 5.1.4 on 2025-01-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_lungsegmentationmodel_alter_medicalimage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
