# Generated by Django 5.1.4 on 2025-01-19 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='segmented_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
        migrations.AlterField(
            model_name='medicalimage',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
